const organiserAccessUrls = [
  //MEETING URLS
  "/createMeeting",
  "/viewAllMeetings",
  "/updateMeeting",
  "/cancelMeeting",
  "/rescheduleMeeting",
  "/updateRsvp",
  "/viewMeeting",
  "/listAttendeesFromPreviousMeeting",
  "/viewMeetingAgendaWithMinutes",
  "/viewMeetingActivities",
  "/getCreateMeetingStep",
  "/updateMeetingAttendance",
  "/generateMOM",
  "/downloadMOM",
  "/giveMomWritePermission",
  // ACTION URLS
  "/actionReAssignRequest",
  "/viewSingleAction",
  "/viewAllActions",
  "/reAssignAction",
  "/viewUserAllActions",
  "/updateAction",
  "/viewActionActivities",
  //MINUTES URL
  "/acceptOrRejectMinutes",
  "/createMinutes",
  "/downloadMinutes",
  "/createAmendmentRequest",
  "/updateAmendmentRequest",
  "/getMeetingListOfAttendees",
  "/deleteMinute",
  "/updateMinute",
  "/acceptMinutes",
  // AGENDA URLS
  "/createAgenda",
  "/createAgendaWithMinutes",
  "/updateAgenda",
  "/deleteAgenda",
];
const attendeesAccessUrls = [
  //MEETING URLS
  "/viewAllMeetings",
  "/updateRsvp",
  "/viewMeeting",
  "/listAttendeesFromPreviousMeeting",
  "/viewMeetingAgendaWithMinutes",
  "/viewMeetingActivities",
  "/getCreateMeetingStep",
  "/updateMeetingAttendance",
  "/downloadMOM",
  // ACTION URLS
  "/actionReAssignRequest",
  "/viewSingleAction",
  "/viewAllActions",
  "/viewUserAllActions",
  "/updateAction",
  "/viewActionActivities",
  //MINUTES URL
  "/acceptOrRejectMinutes",
  "/createMinutes",
  "/downloadMinutes",
  "/createAmendmentRequest",
  "/updateAmendmentRequest",
  "/getMeetingListOfAttendees",
  "/deleteMinute",
  "/updateMinute",
  "/acceptMinutes",
   // AGENDA URLS
   "/createAgenda",
   "/createAgendaWithMinutes",
   "/updateAgenda",
   "/deleteAgenda",
];
module.exports = {
  organiserAccessUrls,
  attendeesAccessUrls,
};
